version: "3.7"

services:
  php:
    image: phplocal
    build: .
    volumes:
      - ./code:/var/www/html
      - ../sw6dev/code/custom/plugins:/var/www/html/custom/plugins
    ports:
      - 80:80
      - 8080:8080
      - 9998:9998
      - 9999:9999
    environment:
      - APP_URL=http://localhost
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
